CREATE TABLE PRODUCT_DETAILS (
    PRD_ID INT PRIMARY KEY,
    PRD_NAME VARCHAR(50),
    PRD_CATEGORY VARCHAR(100),
	PRD_QTY INT,
    PRD_PRICE INT,
	PRD_SUPPLIER VARCHAR(100),
	PRD_ROLE VARCHAR(50),
	PRD_CREATED_TIME TIMESTAMP,
	PRD_UPDATED_TIME TIMESTAMP
);
