CREATE TABLE PRODUCT_DETAILS (
    PRD_ID INT NOT NULL AUTO_INCREMENT,
    PRD_NAME VARCHAR(50),
    PRD_CATEGORY VARCHAR(100),
	PRD_QTY FLOAT(10,2),
    PRD_PRICE FLOAT(10,2),
	PRD_SUPPLIER VARCHAR(100),
	PRD_ROLE VARCHAR(50),
	PRD_CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRD_UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PRD_ID)
);

